/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package InternalPages;
import java.awt.Color;
import static InitPages.DashBoard.MainPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Jeffrey Toquero
 */
public class HomePage extends javax.swing.JInternalFrame {

    /**
     * Creates new form home
     */
    public HomePage() {
        initComponents();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
Color navcolor = new Color(0,102,204);
    Color hover = new Color(0,0,102);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        withdrawpane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        depositpane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        balancepane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 51, 102));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 0, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        withdrawpane.setBackground(new java.awt.Color(0, 102, 204));
        withdrawpane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        withdrawpane.setForeground(new java.awt.Color(204, 255, 255));
        withdrawpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdrawpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdrawpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                withdrawpaneMouseExited(evt);
            }
        });
        withdrawpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InternalPages/Icons/withdraw.png"))); // NOI18N
        withdrawpane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 120));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setForeground(java.awt.SystemColor.controlLtHighlight);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Withdraw");
        withdrawpane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, -1));

        kGradientPanel1.add(withdrawpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, 170));

        depositpane.setBackground(new java.awt.Color(0, 102, 204));
        depositpane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        depositpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depositpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                depositpaneMouseExited(evt);
            }
        });
        depositpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\OneDrive\\Desktop\\Icons and pictures for programming\\deposit.png")); // NOI18N
        depositpane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 2, 160, 110));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.controlLtHighlight);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Deposit");
        depositpane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, -1));

        kGradientPanel1.add(depositpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 170, 170));

        balancepane.setBackground(new java.awt.Color(0, 102, 204));
        balancepane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        balancepane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balancepaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                balancepaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                balancepaneMouseExited(evt);
            }
        });
        balancepane.setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\OneDrive\\Desktop\\Icons and pictures for programming\\balance.png")); // NOI18N
        balancepane.add(jLabel5);
        jLabel5.setBounds(10, 10, 150, 100);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.controlLtHighlight);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("My Balance");
        balancepane.add(jLabel8);
        jLabel8.setBounds(0, 130, 170, 23);

        kGradientPanel1.add(balancepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 170, 170));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.control);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\OneDrive\\Desktop\\Icons and pictures for programming\\bank.png")); // NOI18N
        jLabel2.setText("MINI-BANK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 640, 80));

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 770, 80));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 760, 402));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawpaneMouseClicked
        WithdrawalFrame withdraw = new WithdrawalFrame();
        MainPanel.add(withdraw);
        withdraw.setVisible(true);
        
      
    }//GEN-LAST:event_withdrawpaneMouseClicked

    private void withdrawpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawpaneMouseEntered
        withdrawpane.setBackground(hover);
    }//GEN-LAST:event_withdrawpaneMouseEntered

    private void withdrawpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawpaneMouseExited
        withdrawpane.setBackground(navcolor);
    }//GEN-LAST:event_withdrawpaneMouseExited

    private void depositpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositpaneMouseEntered
        depositpane.setBackground(hover);
    }//GEN-LAST:event_depositpaneMouseEntered

    private void depositpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositpaneMouseExited
        depositpane.setBackground(navcolor);
    }//GEN-LAST:event_depositpaneMouseExited

    private void balancepaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balancepaneMouseEntered
        balancepane.setBackground(hover);
    }//GEN-LAST:event_balancepaneMouseEntered

    private void balancepaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balancepaneMouseExited
        balancepane.setBackground(navcolor);
    }//GEN-LAST:event_balancepaneMouseExited

    private void depositpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositpaneMouseClicked
      depositPage depo = new depositPage();
        MainPanel.add(depo);
        depo.setVisible(true);
    }//GEN-LAST:event_depositpaneMouseClicked

    private void balancepaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balancepaneMouseClicked
     balancePage bal = new balancePage();
     MainPanel.add(bal);
     bal.setVisible(true);
    }//GEN-LAST:event_balancepaneMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel balancepane;
    private javax.swing.JPanel depositpane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPanel withdrawpane;
    // End of variables declaration//GEN-END:variables
}
